# Generated by Django 5.0.3 on 2026-02-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_karma',
            field=models.IntegerField(default=0, help_text='Total karma from all time'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', '-created_at'], name='api_comment_post_id_e8e251_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='api_comment_author__91c0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', '-created_at'], name='api_comment_comment_1c6c05_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['user', '-created_at'], name='api_comment_user_id_a965c5_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='api_post_author__387d67_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='api_post_created_a6c29a_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', '-created_at'], name='api_postlik_post_id_bbc67d_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user', '-created_at'], name='api_postlik_user_id_d25513_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-total_karma'], name='api_user_total_k_7a6244_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['clerk_id'], name='api_user_clerk_i_5fd1aa_idx'),
        ),
    ]
