#!/bin/bash
# CLERK KEY FORMAT REFERENCE
# This file explains the difference between wrong and right formats

echo "================================================"
echo "🔴 WRONG - Base64 Encoded (Current)"
echo "================================================"
echo "Key: pk_test_ZXBpYy1tYXJsaW4tODYuY2xlcmsuYWNjb3VudHMuZGV2JA"
echo "Decoded: epic-marlin-86.clerk.accounts.dev"
echo "❌ This is a DOMAIN, not a publishable key!"
echo "❌ Length: 52 chars"
echo "❌ Vite/Clerk can't use this"
echo ""

echo "================================================"
echo "✅ CORRECT - Real Publishable Key"
echo "================================================"
echo "Key: pk_test_1f2e3d4c5b6a7980aAbBcCdDeEfFgGhHiIjJkKlMnOpPqQrStUvWxXyYzZ"
echo "Decoded: N/A - it's already the real key!"
echo "✅ This is the REAL Clerk publishable key"
echo "✅ Length: 62+ chars"
echo "✅ Starts with pk_test_ (for test) or pk_live_ (for production)"
echo "✅ Contains only alphanumeric characters and underscores"
echo ""

echo "================================================"
echo "🔍 How to Find Real Key"
echo "================================================"
echo "1. Go to https://dashboard.clerk.com"
echo "2. Login with your account"
echo "3. Navigate to 'API Keys' section"
echo "4. Copy 'Publishable Key' (NOT Secret Key)"
echo "5. It should look like: pk_test_2eJ9wQ7SZzxJkE4FpN1vB8mCdE2aH9pL..."
echo ""

echo "================================================"
echo "📊 Key Format Comparison"
echo "================================================"
echo ""
echo "WRONG (Base64):"
echo "- Starts with: pk_test_ZXBpY..."
echo "- Contains: Base64 characters (== at end sometimes)"
echo "- Decoded shows: Domain name"
echo "- Use case: ❌ DO NOT USE"
echo ""
echo "CORRECT (Real):"
echo "- Starts with: pk_test_1f2e3d..."
echo "- Contains: Alphanumeric + underscore only"
echo "- Decoded: Not needed - it's raw"
echo "- Use case: ✅ USE THIS IN .env files"
echo ""

echo "================================================"
echo "💻 Where to Put It"
echo "================================================"
echo ""
echo "Local Development: frontend/.env.local"
echo "VITE_CLERK_PUBLISHABLE_KEY=pk_test_YOUR_REAL_KEY"
echo ""
echo "Production: GitHub Secrets"
echo "VITE_CLERK_PUBLISHABLE_KEY = pk_test_YOUR_REAL_KEY"
echo ""

echo "================================================"
echo "✅ Validation"
echo "================================================"
echo ""
echo "Before using, verify:"
echo "✓ Starts with pk_test_ or pk_live_"
echo "✓ Length is 60+ characters"
echo "✓ No spaces or newlines"
echo "✓ From dashboard.clerk.com (not generated/encoded elsewhere)"
echo "✓ Marked as 'Publishable Key' (not Secret Key)"
echo ""
